### ISSUE TITLE
Initial tasks

### ISSUE THREAD

**Issue by nfreear** [IET-OU/our-journey#1]
Hi @IET-OU/tim-coughlan-game,

Here are some initial things that we may want to do:

 1. [x] —  <del> Get a "name" for the repo. / project name </del> ...
 2. [x] — Put current code (HTML + JS) into GitHub;
 3. [x] — Add OU copyright statements, and attribute Tim C. as author — pull #2;
 4. [x] — Break Javascript into separate JS file(s)(?) CSS? — pull #2;
 5. [x] — Use Node, NPM and `package.json` to manage development tooling, testing etc. — pull #2;
 6. [x] — Add OU logo / branding — maybe to the foot of the HTML?
 7. [x] — `semistandard` Javascript fixes;
 8. [ ] — `pa11y-ci` accessibility fixes;
 9. [x] — Add original artwork/ PDF(s) to Git _(add OU copyright to PDFs)_.
10. [x] — Hosting, via _GitHub Pages_? — discussion on [Teamdesk][]

Further [notes are on Google Docs](https://docs.google.com/document/d/1qaBOfSatwTvanZeopdQHnq3j4Ca0wrqLgDmjODMuu8U/#) ([Teamdesk](https://iet.eu.teamwork.com/desk/#/tickets/250093)).

Yours,

Nick

[Teamdesk][]

[teamdesk]: https://iet.eu.teamwork.com/desk/#/tickets/250100

**Comment by nfreear** [comment]
All done, except perhaps `pally-ci` point.

Closing,


N.
