### ISSUE TITLE
Checklist / suggestions for making the repo. public

### ISSUE THREAD

**Issue by nfreear** [IET-OU/our-journey#38]
## Our-journey open sourcing checklist / suggestions:

Of course, many of these things can be improved after the project is public. Having files sensibly organised, and signalling to the community that you're open to contributions are good to do at/ around _launch_:

 0. [ ] — Add [`package-lock.json`](https://docs.npmjs.com/files/package-lock.json) to the repo. !!
 1. [x] — Re-organise files, after discussion (#22);
 2. [x] — `CONTRIBUTING.md` - v. brief/ initial contribution guidance, including coding-style guide? Link from `README.md` (#37):
    * [GitHub Help: setting-guidelines-for-repository-contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
    * [Example 1 `CONTRIBUTING.md`](https://github.com/discourse/discourse/blob/master/CONTRIBUTING.md)
    * [Example 2 `CONTRIBUTING.md`](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) (not this long !!!)
 3. [x] — [`.editorconfig` file](https://editorconfig.org/) to help contributors and maintainers (in repo. root) (#37);
 4. [x] — Add `.travis.yml` file (in repo. root), and badge to `README.md`:
    * File :- [GitHub: nfreear/our-journey `.travis.yml`](https://github.com/nfreear/our-journey/blob/15-gpl-license/tool/.travis.yml)
    * Docs :- [Travic-CI: javascript-with-nodejs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/)
    * Badge :- https://github.com/nfreear/our-journey/commit/9ee5e2d4d717d77d1ca4956087d8912c5397e50e
 5. [ ] — Check, are attribution and copyright statements OK? Is GPL-3.0+ the correct license?
 6. [x] — Add [`LICENSE.txt` file, GNU GPL-3.0+](https://github.com/nfreear/our-journey/blob/15-gpl-license/LICENSE.txt) (in repo. root) (#15):
     * Based on :- [Gnu.org: `gpl-3.0.txt`](https://gnu.org/licenses/gpl-3.0.txt)
     * Docs :- [Gnu.org: `gpl-3.0.html`](https://gnu.org/licenses/gpl-3.0.en.html)
 7. [x] — Add other mentions of license -- commit: https://github.com/nfreear/our-journey/commit/690b2c1773314d85a075dca84d09d09a15b017b3;
 8. [x] — A "fork-me" ribbon or link -- commit: https://github.com/nfreear/our-journey/commit/690b2c1773314d85a075dca84d09d09a15b017b3;

---

 9. [ ] — [Contributor license agreement (CLA)](https://en.wikipedia.org/wiki/Contributor_License_Agreement) ??
 10. [x] — Google Analytics configuration, #39;
 11. [x] — _Final checks ??_
 12. [x] — _Make public_;
 13. [ ] — _Share on social media etc. !!_
 14. [ ] — __Would a forum be useful? E.g. a Google Group?__
 15. [ ] — ... Later ... [create an issue template, etc.](https://help.github.com/articles/using-templates-to-encourage-high-quality-issues-and-pull-requests-in-your-repository/)?

---
## Links

 * Interesting. Maybe use a [`.github` directory](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/)? (Via: https://github.com/google/fonts/issues/214 & [dear-github](https://github.com/dear-github/dear-github).)
 * GitHub Help: [building-a-strong-community](https://help.github.com/categories/building-a-strong-community/)
 * [Blog: how-to-attract-new-contributors-to-your-open-source-project](https://medium.freecodecamp.org/how-to-attract-new-contributors-to-your-open-source-project-46f8b791d787)
 * [Search: contribution+guidelines+example](https://google.co.uk/search?q=Contribution+guidelines+example)
 * [Search: Open+source+code+of+conduct](https://google.co.uk/search?q=Open+source+code+of+conduct)
 * [Techcrunt: how-we-may-mesh](https://techcrunch.com/2016/03/05/how-we-may-mesh/)
 * [Contributor covenant: adopters](https://contributor-covenant.org/adopters)

---
## Suggested file layout

```
/.github/CONTRIBUTING.md
/.github/ ... issue templates?
/.gitignore
/.travis.yml
/LICENSE.txt
/README.md

...

/docs/  —— Possible location of the GitHub Pages site?
/package-lock.json  —— Add me!

...

/assets/
/dist/
/src/
/style/
/package.json
/index.js
```

---

[[iet:10364720](https://iet.eu.teamwork.com/#tasks/10364720?c=2160051)]
